name: Laravel Sail CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel-sail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor
            node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('**/composer.lock', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install Dependencies
        run: |
          composer install
          npm install

      - name: Setup Laravel Sail
        run: |
          cp .env.example .env
          ./vendor/bin/sail up -d
        env:
          WWWGROUP: 1000

      - name: Run Tests
        run: ./vendor/bin/sail test
